# Generated by Django 4.0.3 on 2022-05-01 15:04

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproducto',
            options={'verbose_name': 'categoria_p', 'verbose_name_plural': 'categorias_p'},
        ),
        migrations.AlterModelOptions(
            name='categoriatienda',
            options={'ordering': ['-created'], 'verbose_name': 'categoria_t', 'verbose_name_plural': 'categorias_t'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-created'], 'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterModelOptions(
            name='tienda',
            options={'ordering': ['-created'], 'verbose_name': 'tienda', 'verbose_name_plural': 'tiendas'},
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio_anterior',
            new_name='precio_old',
        ),
        migrations.RenameField(
            model_name='tienda',
            old_name='image',
            new_name='imagen',
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='image1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='image2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='instock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='like',
            field=models.ManyToManyField(related_name='producto_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tienda',
            name='categorias',
            field=models.ManyToManyField(related_name='categorias_tienda', to='tienda.categoriatienda'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='likes',
            field=models.ManyToManyField(related_name='tienda_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tienda',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categoriatienda',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='categoriatienda',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categorias',
            field=models.ManyToManyField(related_name='categorias_producto', to='tienda.categoriaproducto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tiendas',
            field=models.ManyToManyField(related_name='tiendas', to='tienda.tienda'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
