# Generated by Django 4.0.3 on 2022-05-01 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0002_alter_categoriaproducto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='like',
        ),
        migrations.AddField(
            model_name='producto',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='producto_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categorias',
            field=models.ManyToManyField(related_name='categorias_p', to='tienda.categoriaproducto'),
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tiendas',
        ),
        migrations.AddField(
            model_name='producto',
            name='tiendas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.tienda'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='categorias',
            field=models.ManyToManyField(blank=True, null=True, related_name='categorias_tienda', to='tienda.categoriatienda'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='tienda_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
