# Generated by Django 4.0.3 on 2022-05-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_producto_like_producto_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='tiendas',
            new_name='tienda',
        ),
    ]
