# Generated by Django 4.0.3 on 2022-05-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_comentariop_producto_vender_tienda_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(upload_to='producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='image1',
            field=models.ImageField(upload_to='producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='image2',
            field=models.ImageField(upload_to='producto'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='imagen',
            field=models.ImageField(upload_to='tienda'),
        ),
    ]
