# Generated by Django 3.2 on 2023-06-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tienda',
            old_name='open',
            new_name='is_open',
        ),
    ]
