# Generated by Django 3.2 on 2023-06-04 16:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carro', '0007_remove_contador_prod_id_alter_contador_prod_cantidad_and_more'),
        ('tienda', '0009_rename_open_tienda_is_open'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Tienda',
            new_name='Store',
        ),
    ]
