# Generated by Django 3.2 on 2023-06-04 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_auto_20230604_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='store',
            name='imagen',
        ),
    ]
