# Generated by Django 4.0.3 on 2022-05-12 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_producto_image_alter_producto_image1_and_more'),
        ('carro', '0002_alter_carrito_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contador_Prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('productos', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
            options={
                'verbose_name': 'contador',
                'verbose_name_plural': 'contadores',
            },
        ),
        migrations.AlterField(
            model_name='carrito',
            name='productos',
            field=models.ManyToManyField(blank=True, null=True, related_name='carro_productos', to='carro.contador_prod'),
        ),
    ]
