# Generated by Django 4.0.3 on 2022-05-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0004_remove_contador_prod_productos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contador_prod',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
