# Generated by Django 4.0.3 on 2022-05-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0005_alter_contador_prod_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='contador_prod',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
