# Generated by Django 3.2 on 2023-06-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0010_auto_20230604_1208'),
        ('usuarios', '0014_alter_profile_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='')),
                ('type', models.CharField(choices=[('1', 'profile'), ('2', 'store'), ('3', 'product')], max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi_products', to='tienda.product')),
                ('profiles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi_profiles', to='usuarios.profile')),
                ('stores', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi_business', to='tienda.store')),
            ],
            options={
                'verbose_name': 'multimedia',
                'verbose_name_plural': 'multimedias',
            },
        ),
    ]
