# Generated by Django 4.0.3 on 2022-04-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comentario_comentario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comentario',
            new_name='post',
        ),
    ]
