# Generated by Django 4.0.3 on 2022-04-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_respuesta_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='contenido',
            field=models.TextField(),
        ),
    ]
