# Generated by Django 4.0.3 on 2022-04-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_comentario_contenido_alter_post_contenido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-created'], 'verbose_name': 'comentario', 'verbose_name_plural': 'comentarios'},
        ),
    ]
