# Generated by Django 4.0.3 on 2022-04-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comentario_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='post',
        ),
    ]
