# Generated by Django 4.0.3 on 2022-04-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_approved_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorias',
            field=models.ManyToManyField(related_name='categorias', to='blog.categoria'),
        ),
    ]
