# Generated by Django 4.0.3 on 2022-04-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_options_alter_post_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
