# Generated by Django 4.0.3 on 2022-05-01 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='imagen',
        ),
        migrations.AlterField(
            model_name='profile',
            name='usuario',
            field=models.ManyToManyField(related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
