# Generated by Django 4.0.3 on 2022-05-04 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_profile_options_alter_tipoperfil_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='TipoPerfil',
        ),
    ]
