# Generated by Django 4.0.3 on 2022-05-05 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='usuario',
            new_name='user',
        ),
    ]
