# Generated by Django 4.0.3 on 2022-05-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_rename_usuario_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(upload_to='perfil'),
        ),
    ]
