# Generated by Django 4.0.3 on 2022-05-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_profile_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telf',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
