# Generated by Django 4.0.3 on 2022-05-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_profile_bio_alter_profile_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(blank=True, default='InicioTiendaFull/images/sin-foto.jpg', null=True, upload_to='perfil'),
        ),
    ]
