# Generated by Django 4.0.3 on 2022-05-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_profile_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(blank=True, default='sin-foto.jpg', null=True, upload_to='perfil'),
        ),
    ]
