# Generated by Django 3.2 on 2023-05-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_profile_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Proveedor'), (2, 'Cliente')], default=1),
        ),
    ]
