# Generated by Django 3.2 on 2023-06-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_alter_profile_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='imagen',
        ),
    ]
