# Generated by Django 4.0.3 on 2022-05-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
